export { Testimonials01_ExecutiveHeadshots } from './Testimonials01_ExecutiveHeadshots';
export type { Testimonials01_ExecutiveHeadshotsProps } from './Testimonials01_ExecutiveHeadshots';
export { Testimonials02_Quote3ColGrid } from './Testimonials02_Quote3ColGrid';
export type { Testimonials02_Quote3ColGridProps } from './Testimonials02_Quote3ColGrid';
export { Testimonials03_StarRatingCarousel } from './Testimonials03_StarRatingCarousel';
export type { Testimonials03_StarRatingCarouselProps } from './Testimonials03_StarRatingCarousel';
export { Testimonials04_CustomerMetricsHighlight } from './Testimonials04_CustomerMetricsHighlight';
export type { Testimonials04_CustomerMetricsHighlightProps } from './Testimonials04_CustomerMetricsHighlight';
export { Testimonials05_DarkTestimonialBanner } from './Testimonials05_DarkTestimonialBanner';
export type { Testimonials05_DarkTestimonialBannerProps } from './Testimonials05_DarkTestimonialBanner';
export { Testimonials06_SplitMediaQuote } from './Testimonials06_SplitMediaQuote';
export type { Testimonials06_SplitMediaQuoteProps } from './Testimonials06_SplitMediaQuote';
export { Testimonials07_LogoCloudReviews } from './Testimonials07_LogoCloudReviews';
export type { Testimonials07_LogoCloudReviewsProps } from './Testimonials07_LogoCloudReviews';
export { Testimonials08_VideoTestimonialCards } from './Testimonials08_VideoTestimonialCards';
export type { Testimonials08_VideoTestimonialCardsProps } from './Testimonials08_VideoTestimonialCards';
export { Testimonials09_MasonrySocialWall } from './Testimonials09_MasonrySocialWall';
export type { Testimonials09_MasonrySocialWallProps } from './Testimonials09_MasonrySocialWall';
export { Testimonials10_EnterpriseCaseStudyRow } from './Testimonials10_EnterpriseCaseStudyRow';
export type { Testimonials10_EnterpriseCaseStudyRowProps } from './Testimonials10_EnterpriseCaseStudyRow';
export { Testimonials11_SingleFeaturedHeroQuote } from './Testimonials11_SingleFeaturedHeroQuote';
export type { Testimonials11_SingleFeaturedHeroQuoteProps } from './Testimonials11_SingleFeaturedHeroQuote';
export { Testimonials12_AvatarTickerMarquee } from './Testimonials12_AvatarTickerMarquee';
export type { Testimonials12_AvatarTickerMarqueeProps } from './Testimonials12_AvatarTickerMarquee';
export { Testimonials13_IndustrySpecificTabs } from './Testimonials13_IndustrySpecificTabs';
export type { Testimonials13_IndustrySpecificTabsProps } from './Testimonials13_IndustrySpecificTabs';
export { Testimonials14_FounderLetterStatement } from './Testimonials14_FounderLetterStatement';
export type { Testimonials14_FounderLetterStatementProps } from './Testimonials14_FounderLetterStatement';
export { Testimonials15_Compact2ColMinimal } from './Testimonials15_Compact2ColMinimal';
export type { Testimonials15_Compact2ColMinimalProps } from './Testimonials15_Compact2ColMinimal';
export { Testimonials16_StatsPairedReview } from './Testimonials16_StatsPairedReview';
export type { Testimonials16_StatsPairedReviewProps } from './Testimonials16_StatsPairedReview';
export { Testimonials17_TrustScoreHeader } from './Testimonials17_TrustScoreHeader';
export type { Testimonials17_TrustScoreHeaderProps } from './Testimonials17_TrustScoreHeader';
export { Testimonials18_CustomerMapPinpoints } from './Testimonials18_CustomerMapPinpoints';
export type { Testimonials18_CustomerMapPinpointsProps } from './Testimonials18_CustomerMapPinpoints';
export { Testimonials19_DetailedTimelineReview } from './Testimonials19_DetailedTimelineReview';
export type { Testimonials19_DetailedTimelineReviewProps } from './Testimonials19_DetailedTimelineReview';
export { Testimonials20_SecurityAuditorQuote } from './Testimonials20_SecurityAuditorQuote';
export type { Testimonials20_SecurityAuditorQuoteProps } from './Testimonials20_SecurityAuditorQuote';
export { Testimonials21_CardSliderControls } from './Testimonials21_CardSliderControls';
export type { Testimonials21_CardSliderControlsProps } from './Testimonials21_CardSliderControls';
export { Testimonials22_SpeechBubbleCards } from './Testimonials22_SpeechBubbleCards';
export type { Testimonials22_SpeechBubbleCardsProps } from './Testimonials22_SpeechBubbleCards';
export { Testimonials23_KycSuccessStory } from './Testimonials23_KycSuccessStory';
export type { Testimonials23_KycSuccessStoryProps } from './Testimonials23_KycSuccessStory';
export { Testimonials24_B2CMerchantSpotlight } from './Testimonials24_B2CMerchantSpotlight';
export type { Testimonials24_B2CMerchantSpotlightProps } from './Testimonials24_B2CMerchantSpotlight';
export { Testimonials25_CfoPerspectiveQuote } from './Testimonials25_CfoPerspectiveQuote';
export type { Testimonials25_CfoPerspectiveQuoteProps } from './Testimonials25_CfoPerspectiveQuote';
export { Testimonials26_DeveloperApiPraise } from './Testimonials26_DeveloperApiPraise';
export type { Testimonials26_DeveloperApiPraiseProps } from './Testimonials26_DeveloperApiPraise';
export { Testimonials27_CustomerAwardShowcase } from './Testimonials27_CustomerAwardShowcase';
export type { Testimonials27_CustomerAwardShowcaseProps } from './Testimonials27_CustomerAwardShowcase';
export { Testimonials28_BeforeAfterNarrative } from './Testimonials28_BeforeAfterNarrative';
export type { Testimonials28_BeforeAfterNarrativeProps } from './Testimonials28_BeforeAfterNarrative';
export { Testimonials29_CommunityQuotesWall } from './Testimonials29_CommunityQuotesWall';
export type { Testimonials29_CommunityQuotesWallProps } from './Testimonials29_CommunityQuotesWall';
export { Testimonials30_FinalCalloutQuote } from './Testimonials30_FinalCalloutQuote';
export type { Testimonials30_FinalCalloutQuoteProps } from './Testimonials30_FinalCalloutQuote';
