/**
 * scripts/import-logos.ts
 *
 * Run with:  npx tsx scripts/import-logos.ts   (from builder-app/)
 *
 * Imports the ~360 fictional brand SVGs from `../180+ logos library` into
 * `public/logos/` with URL-safe normalized filenames, and emits a self-contained
 * TypeScript registry at `src/site/lib/logos.ts` (the studio's LogoPicker reads
 * from it).
 *
 * Source filenames look like:
 *   Company=Acme Corp, Style=Badge, Dark mode=True.svg
 *
 * Normalized destination:
 *   public/logos/acme-corp.badge.dark.svg
 *   public/logos/acme-corp.default.light.svg
 *
 * Normalization: lowercase, spaces→dashes, strip commas/ampersands/plus/etc.
 */

import { readdirSync, copyFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));

/** Source folder of raw SVGs, relative to this script. */
const SOURCE_DIR = resolve(SCRIPT_DIR, '../180+ logos library');
/** Where normalized SVGs land, served at `/logos/*.svg`. */
const OUT_DIR = resolve(SCRIPT_DIR, '../public/logos');
/** Generated registry consumed by the studio LogoPicker. */
const REGISTRY_PATH = resolve(SCRIPT_DIR, '../src/site/lib/logos.ts');

/** Normalize a company name into a URL-safe slug. */
function slugify(company: string): string {
  return company
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

/** Parse a source filename into its metadata. Returns null if malformed. */
function parseFilename(
  name: string,
): { company: string; style: 'badge' | 'default'; dark: boolean } | null {
  const m = /^Company=(.*?), Style=(Badge|Default), Dark mode=(True|False)\.svg$/i.exec(
    name,
  );
  if (!m) return null;
  const style = m[2].toLowerCase();
  if (style !== 'badge' && style !== 'default') return null;
  return {
    company: m[1],
    style,
    dark: m[3].toLowerCase() === 'true',
  };
}

interface LogoEntry {
  id: string;
  company: string;
  style: 'badge' | 'default';
  dark: boolean;
  url: string;
}

function main() {
  mkdirSync(OUT_DIR, { recursive: true });

  const files = readdirSync(SOURCE_DIR).filter((f) => f.toLowerCase().endsWith('.svg'));
  const entries: LogoEntry[] = [];
  const skipped: string[] = [];

  for (const file of files) {
    const parsed = parseFilename(file);
    if (!parsed) {
      skipped.push(file);
      continue;
    }
    const slug = slugify(parsed.company);
    const lightDark = parsed.dark ? 'dark' : 'light';
    const destName = `${slug}.${parsed.style}.${lightDark}.svg`;
    copyFileSync(join(SOURCE_DIR, file), join(OUT_DIR, destName));
    entries.push({
      id: destName.replace(/\.svg$/, ''),
      company: parsed.company,
      style: parsed.style,
      dark: parsed.dark,
      url: `/logos/${destName}`,
    });
  }

  // Deterministic ordering for a stable registry.
  entries.sort((a, b) =>
    a.company.localeCompare(b.company) || a.style.localeCompare(b.style) || (a.dark === b.dark ? 0 : a.dark ? 1 : -1),
  );

  /* ---- emit registry -------------------------------------------------- */
  const lines: string[] = [];
  lines.push(`/**
 * Brand logo registry — generated by scripts/import-logos.ts. Do not hand-edit.
 *
 * Self-contained site-kit data: literal entries + plain functions, no imports
 * outside the kit. Consumed by the studio LogoPicker (src/components/studio/
 * panels/LogoPicker.tsx).
 */`);
  lines.push('');
  lines.push(`export type LogoStyle = 'badge' | 'default';`);
  lines.push('');
  lines.push(`export interface BrandLogo {`);
  lines.push(`  id: string;`);
  lines.push(`  company: string;`);
  lines.push(`  style: LogoStyle;`);
  lines.push(`  dark: boolean;`);
  lines.push(`  url: string;`);
  lines.push(`}`);
  lines.push('');
  lines.push(`export const BRAND_LOGOS: BrandLogo[] = [`);
  for (const e of entries) {
    lines.push(
      `  { id: ${JSON.stringify(e.id)}, company: ${JSON.stringify(e.company)}, style: ${JSON.stringify(e.style)}, dark: ${e.dark}, url: ${JSON.stringify(e.url)} },`,
    );
  }
  lines.push(`];`);
  lines.push('');
  lines.push(`export function getLogos(): BrandLogo[] {`);
  lines.push(`  return BRAND_LOGOS;`);
  lines.push(`}`);
  lines.push('');
  lines.push(`export function getLogosForCompany(company: string): BrandLogo[] {`);
  lines.push(`  return BRAND_LOGOS.filter((l) => l.company === company);`);
  lines.push(`}`);
  lines.push('');
  lines.push(`export function searchLogos(q: string): BrandLogo[] {`);
  lines.push(`  const needle = q.trim().toLowerCase();`);
  lines.push(`  if (!needle) return BRAND_LOGOS;`);
  lines.push(`  return BRAND_LOGOS.filter((l) => l.company.toLowerCase().includes(needle));`);
  lines.push(`}`);
  lines.push('');
  writeFileSync(REGISTRY_PATH, lines.join('\n'), 'utf8');

  /* ---- summary -------------------------------------------------------- */
  const companies = new Set(entries.map((e) => e.company));
  const perCompany: Record<string, number> = {};
  const perStyle: Record<string, number> = { badge: 0, default: 0 };
  const perDark: Record<string, number> = { dark: 0, light: 0 };
  for (const e of entries) {
    perCompany[e.company] = (perCompany[e.company] ?? 0) + 1;
    perStyle[e.style]++;
    perDark[e.dark ? 'dark' : 'light']++;
  }

  console.log('==================================================');
  console.log(' import-logos — report');
  console.log('==================================================');
  console.log(`Source files found : ${files.length}`);
  console.log(`Imported          : ${entries.length}`);
  console.log(`Skipped (bad name): ${skipped.length}`);
  if (skipped.length) skipped.forEach((s) => console.log(`  - ${s}`));
  console.log(`Companies         : ${companies.size}`);
  console.log(`Styles            : badge=${perStyle.badge}  default=${perStyle.default}`);
  console.log(`Dark mode         : dark=${perDark.dark}  light=${perDark.light}`);
  console.log('Per company:');
  for (const [c, n] of Object.entries(perCompany).sort((a, b) => a[0].localeCompare(b[0]))) {
    console.log(`  ${c.padEnd(20)} ${n}`);
  }
  console.log(`Registry written  : ${REGISTRY_PATH}`);
  console.log(`Output dir        : ${OUT_DIR}`);
  console.log('==================================================');
}

main();