export { Policies01_SowTermsOfService } from './Policies01_SowTermsOfService';
export type { Policies01_SowTermsOfServiceProps } from './Policies01_SowTermsOfService';
export { Policies02_PhysicalRmaReturns } from './Policies02_PhysicalRmaReturns';
export type { Policies02_PhysicalRmaReturnsProps } from './Policies02_PhysicalRmaReturns';
export { Policies03_SaaSCommercialSla } from './Policies03_SaaSCommercialSla';
export type { Policies03_SaaSCommercialSlaProps } from './Policies03_SaaSCommercialSla';
export { Policies04_GdprPrivacyFramework } from './Policies04_GdprPrivacyFramework';
export type { Policies04_GdprPrivacyFrameworkProps } from './Policies04_GdprPrivacyFramework';
export { Policies05_AirwallexMerchantTerms } from './Policies05_AirwallexMerchantTerms';
export type { Policies05_AirwallexMerchantTermsProps } from './Policies05_AirwallexMerchantTerms';
export { Policies06_AcceptableUsePolicy } from './Policies06_AcceptableUsePolicy';
export type { Policies06_AcceptableUsePolicyProps } from './Policies06_AcceptableUsePolicy';
export { Policies07_SecurityVulnerabilityPolicy } from './Policies07_SecurityVulnerabilityPolicy';
export type { Policies07_SecurityVulnerabilityPolicyProps } from './Policies07_SecurityVulnerabilityPolicy';
export { Policies08_ShippingFreightPolicy } from './Policies08_ShippingFreightPolicy';
export type { Policies08_ShippingFreightPolicyProps } from './Policies08_ShippingFreightPolicy';
export { Policies09_CookiePolicyAndTracking } from './Policies09_CookiePolicyAndTracking';
export type { Policies09_CookiePolicyAndTrackingProps } from './Policies09_CookiePolicyAndTracking';
export { Policies10_IntellectualPropertyCopyright } from './Policies10_IntellectualPropertyCopyright';
export type { Policies10_IntellectualPropertyCopyrightProps } from './Policies10_IntellectualPropertyCopyright';
export { Policies11_AntiMoneyLaunderingAml } from './Policies11_AntiMoneyLaunderingAml';
export type { Policies11_AntiMoneyLaunderingAmlProps } from './Policies11_AntiMoneyLaunderingAml';
export { Policies12_SubprocessorsList } from './Policies12_SubprocessorsList';
export type { Policies12_SubprocessorsListProps } from './Policies12_SubprocessorsList';
export { Policies13_DisputeResolutionEscrow } from './Policies13_DisputeResolutionEscrow';
export type { Policies13_DisputeResolutionEscrowProps } from './Policies13_DisputeResolutionEscrow';
export { Policies14_ConsumerWarrantyNotice } from './Policies14_ConsumerWarrantyNotice';
export type { Policies14_ConsumerWarrantyNoticeProps } from './Policies14_ConsumerWarrantyNotice';
export { Policies15_MasterServiceAgreement } from './Policies15_MasterServiceAgreement';
export type { Policies15_MasterServiceAgreementProps } from './Policies15_MasterServiceAgreement';
